config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :instructions, :ingredients, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resipi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<!-- app/views/recipes/index.html.erb -->

<h1>Recipes</h1>

<%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Instructions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.instructions %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<!-- app/views/recipes/new.html.erb -->

<h1>New Recipe</h1>

<%= form_with(model: @recipe) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :instructions %>
  <%= form.text_area :instructions %>

  <%= form.label :ingredients %>
  <%= form.text_area :ingredients %>

  <%= form.label :author %>
  <%= form.text_field :author %>

  <%= form.submit 'Create Recipe' %>
<% end %>

<%= link_to 'Back', recipes_path %>